questions:
-
 question: Is there even a cat involved?
 peremptory: true
 answertype: tf

-  
 question: Who is the fluffiest cat?
 answertype: multiplechoice
 answeroptions:
 - Leonidas
 - Olive
 highlight: false

-
 question: What is the square root of 4?
 answertype: numeric
 instructions: >
               this is a long line and I'm going to try
               to make it work and let's hope it does.
 validation: 10 > answer > 0

-
 question: What is the best thing for a cat to be?
 answertype: free
 highlight: true
docs: byronpoems
